name: Test and Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.ts'
      - '**.js*'
  workflow_call:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache: ${{ steps.yarn-cache.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.6.0'
      - name: Get cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: dependencies
        run: yarn
  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-mysql@v1
        with:
         mysql-version: '8.0'
         auto-start: true
      - run: mysql -u root -h127.0.0.1 -e 'SELECT version()'
      - run: mysql -u root -h127.0.0.1 -e 'ALTER USER 'root'@'localhost' IDENTIFIED BY "password"'
      # - run: mysql -u root -h127.0.0.1 -e 'flush privileges'
      - name: Flush privileges
        run: mysql -u root -h127.0.0.1 --password=password -e 'FLUSH PRIVILEGES;'
      - run: mysql -u root -h127.0.0.1 --password=password -e 'CREATE DATABASE IF NOT EXISTS Aimly;'
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ${{ needs.dependencies.outputs.cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - name: build
        run: yarn compile
      - name: test
        run: yarn test
        
